@startuml

class Mastermind
class Turn
class Player
class Board
class MakerPlayer
class BreakerPlayer
class Combination
class SecretCombination
class ProposedCombination
class Result
class Goal
class WinnerResult
class Success
class Black
class White
class Position
class Colour
class Red
class Blue
class Yellow
class Green
class Orange
class Purple

Mastermind *-down-> Board
Mastermind *-down-> Turn
Mastermind *-down-> "2" Player

Turn -down-> "2" Player

Player <|-down- MakerPlayer
Player <|-down- BreakerPlayer
MakerPlayer -down-> SecretCombination
BreakerPlayer -down-> Goal
BreakerPlayer -down-> "0..10" ProposedCombination

Combination <|-down- SecretCombination
Combination <|-down- ProposedCombination
Combination *-down-> Position

Board *-down-> SecretCombination
Board o-down-> "0..10" ProposedCombination
Board o-down-> "0..10" Result

Goal <|-down- WinnerResult

Result *-down-> "0..4" Success
Result <|-down- WinnerResult

WinnerResult *-down-> "4" Black

Success <|-down- Black
Success <|-down- White
Black -down-> Position

Position o-down-> Colour

Colour <|-down- Red
Colour <|-down- Blue
Colour <|-down- Yellow
Colour <|-down- Green
Colour <|-down- Orange
Colour <|-down- Purple


@enduml